functionsDirectory = "/data/.openclaw/workspace/maboiteajouets-v2/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[build]
publish = "/data/.openclaw/workspace/maboiteajouets-v2/.next"
publishOrigin = "ui"
commandOrigin = "config"
command = "npm run build"
functions = "/data/.openclaw/workspace/maboiteajouets-v2/netlify/functions"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"
npm_package_engines_node = "20"
DATABASE_URL = "postgresql://netlifydb_owner:npg_uM9rTGXN2OUI@ep-soft-night-ajfp1t6i.c-3.us-east-2.db.netlify.com/netlifydb?sslmode=require"
ADMIN_API_KEY = "admin123"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]