const { Pool } = require("pg");

const DATABASE_URL =
  "postgresql://netlifydb_owner:npg_uM9rTGXN2OUI@ep-soft-night-ajfp1t6i.c-3.us-east-2.db.netlify.com/netlifydb?sslmode=require";

const pool = new Pool({
  connectionString: DATABASE_URL,
});

const PRODUCTS = [
  {
    id: "p-001",
    slug: "ours-en-peluche-tout-doux",
    name: "Ours en peluche tout doux",
    category: "peluches",
    categoryName: "Peluches",
    description: "Un compagnon câlin en coton bio, parfait pour les câlins et les rêves.",
    longDescription:
      "Notre ours en peluche est confectionné en coton biologique certifié. Sa douceur exceptionnelle et sa taille idéale en font le compagnon parfait pour accompagner votre enfant dans ses premiers rêves. Certifié CE et sans substances nocives.",
    price: 19.9,
    oldPrice: 24.9,
    rating: 4.9,
    reviewCount: 128,
    age: ["0-12m", "1-3", "3-5"],
    images: ["🧸"],
    badge: "Meilleure vente",
    inStock: true,
    stockCount: 42,
    materials: ["Coton biologique", "Rembourrage polyester recyclé"],
    dimensions: "30 cm",
    safety: ["Certifié CE", "Sans BPA", "Testé dermatologiquement"],
    color: "coral",
    bgClass: "bg-pinkwash",
  },
  {
    id: "p-002",
    slug: "train-en-bois",
    name: "Train en bois",
    category: "vehicules",
    categoryName: "Véhicules",
    description: "Locomotive et wagons colorés en bois FSC, pour de folles aventures.",
    price: 24.9,
    rating: 4.8,
    reviewCount: 76,
    age: ["1-3", "3-5"],
    images: ["🚂"],
    badge: "Coup de cœur",
    inStock: true,
    stockCount: 30,
    materials: ["Bois FSC", "Peinture à base d'eau"],
    dimensions: "25 x 8 x 6 cm",
    safety: ["Certifié CE", "Peinture non toxique"],
    color: "sunflower",
    bgClass: "bg-[#FFF7E0]",
  },
  {
    id: "p-003",
    slug: "boite-creative",
    name: "Boîte créative",
    category: "jouets-educatifs",
    categoryName: "Jouets éducatifs",
    description: "Kit complet pour éveiller la créativité : gommettes, feutres, pochoirs.",
    price: 29.9,
    rating: 4.7,
    reviewCount: 54,
    age: ["3-5", "6-8"],
    images: ["🎨"],
    badge: "Nouveau",
    inStock: true,
    stockCount: 18,
    materials: ["Carton recyclé", "Matériaux non toxiques"],
    dimensions: "30 x 25 x 5 cm",
    color: "grape",
    bgClass: "bg-[#F3EDFA]",
  },
  {
    id: "p-004",
    slug: "trottinette-enfant",
    name: "Trottinette enfant",
    category: "jeux-exterieur",
    categoryName: "Jeux d'extérieur",
    description: "Trottinette 3 roues stable et légère, pour découvrir l'extérieur.",
    price: 49.9,
    oldPrice: 59.9,
    rating: 4.6,
    reviewCount: 89,
    age: ["3-5", "6-8"],
    images: ["🛴"],
    badge: "Promo",
    inStock: true,
    stockCount: 15,
    materials: ["Aluminium", "Plastique renforcé"],
    dimensions: "60 x 30 x 70 cm",
    safety: ["Certifié CE", "Freins arrière"],
    color: "sky",
    bgClass: "bg-skywash",
  },
  {
    id: "p-005",
    slug: "robot-educatif",
    name: "Robot éducatif",
    category: "jouets-educatifs",
    categoryName: "Jouets éducatifs",
    description: "Robot interactif qui apprend les lettres, chiffres et musiques.",
    price: 59.9,
    rating: 4.8,
    reviewCount: 142,
    age: ["3-5", "6-8"],
    images: ["🤖"],
    badge: "Meilleure vente",
    inStock: true,
    stockCount: 22,
    materials: ["Plastique ABS recyclé"],
    dimensions: "25 cm de haut",
    safety: ["Certifié CE", "Volume limité"],
    color: "mint",
    bgClass: "bg-[#E4F7F5]",
  },
  {
    id: "p-006",
    slug: "maison-de-poupee",
    name: "Maison de poupée",
    category: "jouets-educatifs",
    categoryName: "Jouets éducatifs",
    description: "Grande maison en bois avec mobilier inclus, pour des heures de jeu.",
    price: 89.9,
    oldPrice: 109.9,
    rating: 4.9,
    reviewCount: 67,
    age: ["3-5", "6-8"],
    images: ["🏠"],
    badge: "Promo",
    inStock: true,
    stockCount: 8,
    materials: ["Bois FSC", "Tissus coton"],
    dimensions: "60 x 30 x 70 cm",
    color: "coral",
    bgClass: "bg-pinkwash",
  },
  {
    id: "p-007",
    slug: "lapin-blanc-doudou",
    name: "Lapin blanc doudou",
    category: "peluches",
    categoryName: "Peluches",
    description: "Petit lapin blanc en peluche ultra-douce, avec ses longues oreilles.",
    price: 16.9,
    rating: 4.9,
    reviewCount: 94,
    age: ["0-12m", "1-3"],
    images: ["🐰"],
    badge: "Coup de cœur",
    inStock: true,
    stockCount: 35,
    materials: ["Coton biologique", "Rembourrage recyclé"],
    dimensions: "22 cm",
    color: "coral",
    bgClass: "bg-pinkwash",
  },
  {
    id: "p-008",
    slug: "dinosaure-vert-cuddly",
    name: "Dinosaure vert câlin",
    category: "peluches",
    categoryName: "Peluches",
    description: "Un dinosaure tout doux et rigolo pour les petites aventures.",
    price: 22.5,
    rating: 4.7,
    reviewCount: 61,
    age: ["1-3", "3-5"],
    images: ["🦕"],
    inStock: true,
    stockCount: 24,
    materials: ["Peluche recyclée"],
    dimensions: "28 cm",
    color: "leaf",
    bgClass: "bg-[#EFF7DE]",
  },
  {
    id: "p-009",
    slug: "boite-activites-hape",
    name: "Boîte d'activités Hape",
    category: "jouets-bebe",
    categoryName: "Jouets bébé",
    description: "Boîte d'activités 5 faces avec engrenages, boules, blocs, labyrinthe et miroir pour éveiller la motricité.",
    longDescription:
      "Cette boîte d'activités Hape à 5 faces offre une multitude d'activités pour développer la motricité fine et l'exploration sensorielle de votre enfant. Chaque face propose des jeux différents : engrenages en forme de fleurs, boules multicolores dans un labyrinthe, blocs pédagogiques, et un miroir pour refléter le sourire de bébé. La face recto présente une ferme colorée avec pièces encastrables (animaux), les engrenages à tourner, et un labyrinthe aquatique. Dimensions : L 25.5 x H 21.5 cm. Certifiée aux normes de sécurité CE et NF EN 71. Garantie 2 ans.",
    price: 36.4,
    rating: 4.8,
    reviewCount: 112,
    age: ["0-12m", "1-3"],
    images: ["/products/hape-boite-1.jpg", "/products/hape-boite-2.jpg", "/products/hape-boite-3.jpg", "/products/hape-boite-4.jpg", "/products/hape-boite-5.jpg"],
    badge: "Nouveau",
    inStock: true,
    stockCount: 25,
    materials: ["Bois massif", "Peinture à base d'eau", "Miroir"],
    dimensions: "L 25.5 x H 21.5 cm",
    safety: ["Certifié CE", "NF EN 71-1/2/3", "Garantie 2 ans"],
    color: "sky",
    bgClass: "bg-[#F0F7FE]",
  },
  {
    id: "p-010",
    slug: "fusee-lumineuse",
    name: "Fusée lumineuse",
    category: "vehicules",
    categoryName: "Véhicules",
    description: "Fusée avec lumières et sons pour de folles missions spatiales.",
    price: 34.9,
    rating: 4.6,
    reviewCount: 47,
    age: ["3-5", "6-8"],
    images: ["🚀"],
    badge: "Nouveau",
    inStock: true,
    stockCount: 20,
    materials: ["Plastique ABS"],
    dimensions: "35 cm de haut",
    safety: ["Volume limité", "Certifié CE"],
    color: "grape",
    bgClass: "bg-[#F3EDFA]",
  },
  {
    id: "p-011",
    slug: "puzzle-animaux",
    name: "Puzzle animaux 24 pièces",
    category: "jouets-educatifs",
    categoryName: "Jouets éducatifs",
    description: "Puzzle en bois avec les animaux de la ferme, épais et facile à manipuler.",
    price: 14.9,
    rating: 4.7,
    reviewCount: 82,
    age: ["1-3", "3-5"],
    images: ["🧩"],
    inStock: true,
    stockCount: 55,
    materials: ["Bois FSC", "Encre végétale"],
    dimensions: "30 x 22 cm",
    color: "mint",
    bgClass: "bg-[#E4F7F5]",
  },
  {
    id: "p-012",
    slug: "ballon-multicolore",
    name: "Ballon multicolore",
    category: "jeux-exterieur",
    categoryName: "Jeux d'extérieur",
    description: "Ballon léger et coloré, parfait pour jouer au parc.",
    price: 9.9,
    rating: 4.5,
    reviewCount: 33,
    age: ["3-5", "6-8", "9+"],
    images: ["⚽"],
    inStock: true,
    stockCount: 100,
    materials: ["Caoutchouc naturel"],
    dimensions: "Ø 22 cm",
    color: "tangerine",
    bgClass: "bg-[#FFEED9]",
  },
  {
    id: "p-013",
    slug: "cuisine-de-jeu",
    name: "Cuisine de jeu en bois",
    category: "jouets-educatifs",
    categoryName: "Jouets éducatifs",
    description: "Grande cuisine en bois avec accessoires : casseroles, fruits, ustensiles.",
    price: 119.0,
    oldPrice: 149.0,
    rating: 4.9,
    reviewCount: 71,
    age: ["3-5", "6-8"],
    images: ["🍳"],
    badge: "Promo",
    inStock: true,
    stockCount: 6,
    materials: ["Bois FSC", "Peinture à base d'eau"],
    dimensions: "90 x 30 x 100 cm",
    color: "coral",
    bgClass: "bg-pinkwash",
  },
  {
    id: "p-014",
    slug: "jeu-de-memoire",
    name: "Jeu de mémoire",
    category: "jeux-de-societe",
    categoryName: "Jeux de société",
    description: "36 cartes en bois avec animaux mignons pour développer la mémoire.",
    price: 18.5,
    rating: 4.8,
    reviewCount: 45,
    age: ["3-5", "6-8"],
    images: ["🃏"],
    badge: "Coup de cœur",
    inStock: true,
    stockCount: 28,
    materials: ["Bois FSC"],
    dimensions: "Boîte 22 x 22 cm",
    color: "grape",
    bgClass: "bg-[#F3EDFA]",
  },
];

async function initDb() {
  const client = await pool.connect();
  try {
    console.log("🔄 Creating products table...");

    await client.query(`
      DROP TABLE IF EXISTS products;
      
      CREATE TABLE products (
        id TEXT PRIMARY KEY,
        slug TEXT UNIQUE NOT NULL,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        categoryName TEXT NOT NULL,
        description TEXT NOT NULL,
        longDescription TEXT,
        price DECIMAL(10, 2) NOT NULL,
        oldPrice DECIMAL(10, 2),
        rating DECIMAL(3, 1),
        reviewCount INTEGER,
        age TEXT[],
        images TEXT[],
        badge TEXT,
        inStock BOOLEAN,
        stockCount INTEGER,
        materials TEXT[],
        dimensions TEXT,
        safety TEXT[],
        color TEXT,
        bgClass TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);

    console.log("✓ Table created");

    console.log("🔄 Inserting products...");

    for (const product of PRODUCTS) {
      await client.query(
        `INSERT INTO products (
          id, slug, name, category, categoryName, description, longDescription,
          price, oldPrice, rating, reviewCount, age, images, badge, inStock,
          stockCount, materials, dimensions, safety, color, bgClass
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)`,
        [
          product.id,
          product.slug,
          product.name,
          product.category,
          product.categoryName,
          product.description,
          product.longDescription || null,
          product.price,
          product.oldPrice || null,
          product.rating || null,
          product.reviewCount || null,
          product.age || [],
          product.images || [],
          product.badge || null,
          product.inStock,
          product.stockCount,
          product.materials || [],
          product.dimensions || null,
          product.safety || [],
          product.color || null,
          product.bgClass || null,
        ]
      );
    }

    console.log(`✓ Inserted ${PRODUCTS.length} products`);

    console.log("✅ Database initialized successfully!");
  } catch (error) {
    console.error("❌ Error:", error.message);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

initDb();
